# Generated by Django 3.2.9 on 2021-11-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('review', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=3)),
                ('checkin', models.CharField(max_length=10)),
                ('checkout', models.CharField(max_length=10)),
            ],
        ),
    ]
